[package]
name = "multimode-cli"
version = "0.1.0"
edition = "2021"
authors = ["Teoman Ata Korkmaz <teoata17@gmail.com>"]
description = "A multi-mode CLI application with different screens"

[dependencies]
crossterm = "0.27"
